### ISSUE TITLE
blog link broken

### ISSUE THREAD

**Issue by zachthemystic** [DerelictOrg/DerelictAllegro5#3]
http://dblog.aldacron.net/derelictallegro5/
is broken for me

**Comment by mdparker** [comment]
Yeah, I don't recall the date on that blog post. It's probably in the archive, but given that the link isn't using the date in the format, it isn't being picked up by the redirect. There are problems with this package anyway, IIRC, so I'm not sure if I'm going to migrate it to the new DerelictUtil going forward as I have the other packages. I may just deprecate it. [Siegelord's binding](https://github.com/SiegeLord/DAllegro5) is probably a better option at this point. I'll figure it out in the coming days.
