### ISSUE TITLE
macOS nothrow @nogc errors

### ISSUE THREAD

**Issue by joelcnz** [DerelictOrg/DerelictAllegro5#5]
DerelictAllegro5.run( {
		al_init();

		ALLEGRO_EVENT_QUEUE* QUEUE;

		QUEUE = al_create_event_queue; // error here!

		return 0;
	});

Joels-MacBook-Pro:AllegroDere joelchristensen$ dub
Performing "debug" build using dmd for x86_64.
derelict-util 2.0.6: target for configuration "library" is up to date.
derelict-allegro5 1.0.2: target for configuration "library" is up to date.
alleg ~master: building configuration "application"...
source/main.d(31,11): Error: cannot implicitly convert expression (al_create_event_queue) of type extern (C) ALLEGRO_EVENT_QUEUE*
 function() nothrow @nogc to ALLEGRO_EVENT_QUEUE*
dmd failed with exit code 1.

**Comment by mdparker** [comment]
You forgot your parentheses:

```d
QUEUE = al_create_event_queue();
```
Please keep in mind that with Derelict you are calling function pointers, so the parentheses are not optional.

**Comment by joelcnz** [comment]
Thanks.
